### ISSUE TITLE
Managed Database & Backend Setup

### ISSUE THREAD

**Issue by ademuh** [ademuh/devops13-dumbways-s1#13]
- [x] Server Database di IDCH
- [x] SSH Key antar server
- [x] Fork dan clone repo dumbflix-backend
- [x] Install mysql di server database
- [x] setup database , make user, privileges
- [x] Bikin domain API Cloudflare
- [x] setup app backend (integration to database, reverse prxy, and multilevel domain)
- [x] setup Front-end + Back-end
- [x] Certbot untuk SSL
- [x] Documentation

**Comment by yuuzukatsu** [comment]
wow
