### ISSUE TITLE
Ade ngajak ribut

### ISSUE THREAD

**Issue by awooooool** [ademuh/devops13-dumbways-s1#8]
### Windows version

Windows 10 Enterprise 21H2

### OS build

19044.1889

### Platform

x64

### Area(s) with issue?

Ade

### Steps to reproduce

Coba aja ngomong sama Ade, pasti ngajak ribut

### ✔️ Expected Behavior

Ade ga ngajak ribut

### ❌ Actual Behavior

Ade ngajak ribut

**Comment by ademuh** [comment]
# Resolution

gw ngajak ribut

**Comment by yuuzukatsu** [comment]
i have the same problem with Windows 10 version 20H2 Build 19042.1706
currently still fighting with Ade
please fix

**Comment by yuuzukatsu** [comment]
> # Resolution
> gw ngajak ribut

this isn't a fix
please push a proper fix
